runtime: php55
api_version: 1

handlers:
- url: /index\.html
  static_files: www/webpage.html
  upload: www/webpage.html
  
- url: (.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true