runtime: php55
api_version: 1

handlers:
- url: /
  static_files: www/webpage.html
  upload: www/webpage.html
  
- url: /www/.*(gif|png|jpg)
  static_dir: www
  upload: www/.*\.(gif|png|jpg)
  application_readable: true